language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-2.0.0

before_script:
  - git clone https://github.com/beanstalkd/beaneater.git /tmp/beaneater
  - git clone https://github.com/nesquena/backburner.git /tmp/backburner
  - rake start_test_server

script:
  - cd /tmp/beaneater
  - rake
  - cd /tmp/backburner
  - rake
