language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode

before_script:
  - bundle config
  - rake start_gemerald_beanstalk_test_server &
  - git clone https://github.com/beanstalkd/beaneater.git /tmp/beaneater
  - BUNDLE_GEMFILE=/tmp/beaneater/Gemfile bundle install
  - git clone https://github.com/nesquena/backburner.git /tmp/backburner
  - BUNDLE_GEMFILE=/tmp/backburner/Gemfile bundle install

script:
  - rake test
  - sudo sed -e 's/^\(127.0.0.1.*\)$/\1 coveralls.io/' -i '' /etc/hosts
  - cd /tmp/beaneater
  - BUNDLE_GEMFILE=/tmp/beaneater/Gemfile bundle exec rake test:full
  - cd /tmp/backburner
  - BUNDLE_GEMFILE=/tmp/backburner/Gemfile bundle exec rake

matrix:
  allow_failures:
    - rvm: jruby-19mode
